version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - gochecknoinits
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/jamesalexatkin/tfl-golang
            - github.com/fatih/color
            - github.com/mattn/go-isatty
            - github.com/urfave/cli/v3
            - github.com/joho/godotenv
            - github.com/jamesalexatkin/tfl-cli
    revive:
      rules:
        - name: package-comments
          disabled: true
    tagliatelle:
      case:
        rules:
          json: snake
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
